import { ClassNames } from '@emotion/react';
import {
    AccountBalance,
    AccountBalanceWallet,
    AddShoppingCart,
    Alarm,
    AllInbox,
    AttachMoney,
    Autorenew,
    Backup,
    BatteryChargingFull,
    BeachAccess,
    Beenhere,
    Block,
    Bluetooth,
    Book,
    Bookmark,
    BugReport,
    Build,
    Cached,
    CalendarToday,
    Call,
    Camera,
    Chat,
    Check,
    Cloud,
    Code,
    Computer,
    Dashboard,
    Delete,
    Directions,
    Done,
    Download,
    Edit,
    Email,
    Event,
    Face,
    Favorite,
    FileCopy,
    Filter,
    Fingerprint,
    FitnessCenter,
    FlashOn,
    Flight,
    Folder,
    Forum,
    Gamepad,
    Gavel,
    GetApp,
    Group,
    Headset,
    Home,            
    Hotel,
    Image,
    Info,
    Keyboard,
    Language,
    Laptop,
    Link,
    List,
    LocalCafe,
    LocalDining,
    Lock,
    Loop,
    Map,
    Memory,
    Message,
    Mic,
    Mood,
    MusicNote,
    Notifications,
    OfflineBolt,
    Pageview,
    Palette,
    PanTool,
    Payment,
    People,
    Pets,
    Photo,
    Power,
    Print,
    Public,
    Radio,
    Restaurant,
    Room,
    Save,
    School,
    Search,
    Security,
    Send,
    Settings,
    Share,
    ShoppingCart,
    SignalCellularAlt,
    Star,
    Store,
    Sync,
    ThumbUp,
    Timer,
    TrendingUp,
    VerifiedUser,
    Visibility,
    VolumeUp,
    Warning,
    Wifi,
    Work,
    ZoomIn,
    ZoomOut,
    ArrowForward,
    ArrowBack,
    Brightness4,
    Brightness5,
    Brush,
    CameraAlt,
    Category,
    CheckCircle,
    CloudQueue,
    Create,
    Crop,
    DirectionsBike,
    DirectionsBus,
    DirectionsCar,
    DirectionsRun,
    DirectionsWalk,
    EmojiEmotions,
    EmojiEvents,
    EmojiFlags,
    EmojiFoodBeverage,
    EmojiNature,
    EmojiObjects,
    EmojiPeople,
    EmojiSymbols,
    EmojiTransportation,
    Equalizer,
    Error,
    Explore,
    Extension,
    FaceRetouchingNatural,
    FactCheck,
    FastForward,
    FavoriteBorder,
    FileDownload,
    FilePresent,
    FilterDrama,
    FilterVintage,
    FingerprintOutlined,
    FireExtinguisher,
    Flag,
    FlashlightOn,
    FlightLand,
    Flip,
    FolderOpen,
    FontDownload,
    Forest,
    FreeBreakfast,
    Functions,
    GTranslate,
    Games,
    GpsFixed,
    GraphicEq,
    GridView,
    GroupWork,
    Handyman,
    HistoryEdu,
    HolidayVillage,
    HomeRepairService,
    House,
    HowToReg,
    HowToVote,
    ElectricalServicesOutlined,
    DensitySmall,
  } from '@mui/icons-material';

  export const getIconComponent =(
    iconName: string,
    textColor? : string,
    fontSize? :string
  ): JSX.Element => {
    const defaultFontSize ="27px";
    const defaultTextColor = "text-orange-600";

    const iconProps ={
        sx : {fontSize: fontSize || defaultFontSize},
        ClassNames: `${defaultTextColor} &{textColor || ""}`.trim(),
    };

    switch (iconName) {
        case "DensitySmall":
            return <DensitySmall {...iconProps} />;
        case "ElectricalServicesOutlined":
            return <ElectricalServicesOutlined {...iconProps} />
        case "AccountBalance" :
            return <AccountBalance {...iconProps} />
        case "AccountBalanceWallet":
            return <AccountBalanceWallet {...iconProps} />    

    }






}